[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
monitor_dtr = 0
monitor_rts = 0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DUSER_SETUP_LOADED=1
    -DST7796_DRIVER=1
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=480
    -DTFT_MISO=19
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=4
    -DTFT_DC=16
    -DTFT_RST=-1
    -DTFT_HW_RST=17
    -DTFT_RST_ACTIVE_LOW=1
    -DSPI_FREQUENCY=10000000
    -DSPI_READ_FREQUENCY=5000000
    -DTOUCH_CS=14
    -DSPI_TOUCH_FREQUENCY=1000000
    -DI2C_SDA_GPIO=22
    -DI2C_SCL_GPIO=21
    -DMCP4231_SDI_PIN=19

build_src_filter =
    +<main.cpp>

lib_deps =
    bodmer/TFT_eSPI

upload_flags =
    --before
    no_reset
    --after
    no_reset

upload_speed = 115200

[env:esp32dev_lvgl_demo]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
monitor_dtr = 0
monitor_rts = 0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DUSER_SETUP_LOADED=1
    -DST7796_DRIVER=1
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=480
    -DTFT_MISO=19
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=4
    -DTFT_DC=16
    -DTFT_RST=-1
    -DTFT_HW_RST=17
    -DTFT_RST_ACTIVE_LOW=1
    -DSPI_FREQUENCY=10000000
    -DSPI_READ_FREQUENCY=5000000
    -DLV_CONF_INCLUDE_SIMPLE

build_src_filter =
    +<lvgl_demo.cpp>

lib_deps =
    bodmer/TFT_eSPI
    lvgl/lvgl @ ^8.3.11

upload_flags =
    --before
    no_reset
    --after
    no_reset

upload_speed = 115200

[env:esp32dev_ili9488]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
monitor_dtr = 0
monitor_rts = 0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DUSER_SETUP_LOADED=1
    -DILI9488_DRIVER=1
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=480
    -DTFT_MISO=19
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=4
    -DTFT_DC=16
    -DTFT_RST=17
    -DSPI_FREQUENCY=10000000
    -DSPI_READ_FREQUENCY=5000000
    -DTOUCH_CS=14
    -DSPI_TOUCH_FREQUENCY=1000000

build_src_filter =
    +<main.cpp>

lib_deps =
    bodmer/TFT_eSPI

upload_speed = 921600

[env:esp32dev_ili9486]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
monitor_dtr = 0
monitor_rts = 0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DUSER_SETUP_LOADED=1
    -DILI9486_DRIVER=1
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=480
    -DTFT_MISO=19
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=4
    -DTFT_DC=16
    -DTFT_RST=17
    -DSPI_FREQUENCY=10000000
    -DSPI_READ_FREQUENCY=5000000
    -DTOUCH_CS=14
    -DSPI_TOUCH_FREQUENCY=1000000

build_src_filter =
    +<main.cpp>

lib_deps =
    bodmer/TFT_eSPI

upload_speed = 921600

[env:esp32dev_ili9486_nocs]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
monitor_dtr = 0
monitor_rts = 0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DUSER_SETUP_LOADED=1
    -DILI9486_DRIVER=1
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=480
    -DTFT_MISO=19
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=-1
    -DTFT_DC=16
    -DTFT_RST=17
    -DSPI_FREQUENCY=10000000
    -DSPI_READ_FREQUENCY=5000000
    -DTOUCH_CS=14
    -DSPI_TOUCH_FREQUENCY=1000000

build_src_filter =
    +<main.cpp>

lib_deps =
    bodmer/TFT_eSPI

upload_speed = 921600

[env:esp32dev_ili9486_swap_spi]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
monitor_dtr = 0
monitor_rts = 0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DUSER_SETUP_LOADED=1
    -DILI9486_DRIVER=1
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=480
    -DTFT_MISO=23
    -DTFT_MOSI=19
    -DTFT_SCLK=18
    -DTFT_CS=4
    -DTFT_DC=16
    -DTFT_RST=17
    -DSPI_FREQUENCY=10000000
    -DSPI_READ_FREQUENCY=5000000
    -DTOUCH_CS=14
    -DSPI_TOUCH_FREQUENCY=1000000

build_src_filter =
    +<main.cpp>

lib_deps =
    bodmer/TFT_eSPI

upload_speed = 921600

[env:esp32dev_ili9486_swap_ctrl]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
monitor_dtr = 0
monitor_rts = 0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DUSER_SETUP_LOADED=1
    -DILI9486_DRIVER=1
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=480
    -DTFT_MISO=19
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=4
    -DTFT_DC=17
    -DTFT_RST=16
    -DSPI_FREQUENCY=10000000
    -DSPI_READ_FREQUENCY=5000000
    -DTOUCH_CS=14
    -DSPI_TOUCH_FREQUENCY=1000000

build_src_filter =
    +<main.cpp>

lib_deps =
    bodmer/TFT_eSPI

upload_speed = 921600

[env:esp32dev_ili9486_noreset]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
monitor_dtr = 0
monitor_rts = 0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DUSER_SETUP_LOADED=1
    -DILI9486_DRIVER=1
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=480
    -DTFT_MISO=19
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=4
    -DTFT_DC=16
    -DTFT_RST=-1
    -DSPI_FREQUENCY=10000000
    -DSPI_READ_FREQUENCY=5000000
    -DTOUCH_CS=14
    -DSPI_TOUCH_FREQUENCY=1000000

build_src_filter =
    +<main.cpp>

lib_deps =
    bodmer/TFT_eSPI

upload_speed = 921600
